---
sudo: required
language: python
services:
  - docker
env:
  - scenario: default
before_install:
  - sudo apt-get -qq update
install:
  - pip install ansible==2.9.5
  - pip install molecule[docker]==2.22
script:
  - travis_wait 50 molecule lint -s $scenario
notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
